# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            WunderWay
tagline:          The Wunderkraut Intranet
description:      How we run our company and deliver projects
url:              http://wunderkraut.com

author:
  name:           Wunderkraut
  url:            https://twitter.com/Wunderkraut

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/Wunderkraut/wunderway
  branch:         https://github.com/Wunderkraut/wunderway/tree/gh-pages
